<b>EE393 Pyhon for Engineers -23.11.2020</b><br>

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

To use Numpy, we first need to import the numpy package

In [ ]:
import numpy as np

In [ ]:
#SPEED comparison between numpy and core python
import numpy as np
import time
 
# size of arrays and lists
size = 100000000  
 
# declaring lists
list1 = range(size)
list2 = range(size)
# declaring arrays
array1 = np.arange(size)  
array2 = np.arange(size)
 
# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
 
# calculating execution time
print("Time taken by Lists :", 
      (time.time() - initialTime),
      "seconds")
 
# NumPy array
initialTime = time.time()
resultantArray = array1 * array2
# calculating execution time 
print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")

In [ ]:
#creating 1D arrays (vectors)
# as vectors from lists
a = np.array([1,3,5,7,9]) #a is a 1-d array
b = np.array([3,5,6,7,9])
c = a + b
print (c)
print (type(c))
print (c.shape)
print (c.dtype)
#Accessing array elements
print ("First: ", a[0])
print ("Last minus 1: ", a[-2])
for x in a:   #ndarrays are iterable
    print (x, end=" ")

In [ ]:
#numpy data types
import numpy as np 
a=np.longdouble(27)
print (np.dtype(a))
print (a)

In [ ]:
#normal Python programming tools are used!
print (c[0])
print (c) #c is an nd array
for x in c:
    print (x, type(x))
c = np.append(c,77) #append a new value at the end of array
for i in c: print (i,end= " ")

In [ ]:
#CREATING A MATRIX
#more than one dimension!
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]  # create a list 
a = np.array(l)  # convert a list to an array 
print(a) 
print (a.shape)
print(a.dtype)  # get type of an array 
M = np.array([[1, 2], [3, 4]])
print (M.shape)
print (M.dtype)

In [ ]:
#checking number of dimensions, shape and size
import numpy as np
a = np.array(1+2j)
b = np.array([0,2,4,6,8])
c = np.array([[1,2,3], [5,8,13]])
c2 = np.array([[1,2,3], [5,8,13],[1,1,1]])
d = np.array([[[1, 2, 3,0], [5,8,13,0]], 
              [[21,34,55,0], [89,144,233,0]], 
              [[21,34,55,0], [89,144,233,0]]])
print("dimension of a: {}, shape: {}".format(a.ndim, a.shape))
print("dimension of b: {}, shape: {}".format(b.ndim, b.shape))
print("dimension of c: {}, shape: {}".format(c.ndim, c.shape))
print("dimension of c2: {}, shape: {}".format(c2.ndim, c2.shape))
print("dimension of d: {}, shape: {}, size: {}".format(d.ndim, d.shape, d.size))
print (d)

In [ ]:
# minimum dimensions- the result is a 2x2 array
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)
print (a.shape)

In [ ]:
#we can specify dtype explicitly
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)
b = np.array([1, 2, 3], dtype = float) 
print (b)

In [ ]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)
#values are randomly assigned values in the memory

In [ ]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print (x)

In [ ]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print (x)
y = np.ones([5,3], dtype=int)
print (y)

In [ ]:
#identity matrix
I = np.eye(5)
print (I)

In [ ]:
import numpy as np
# create a list
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]    
a = np.array(l) # convert a list to an array
print(a)
print (a.shape)
print(a.dtype) # get type of an array
print ("row:", a[0])
print ("column:", a[:,1])

M = np.array([[1, 2], [3, 4]])
print (M.shape)
print (M.dtype)

M = np.array([[1, 2], [3, 4]], dtype=complex)
print (M)

In [ ]:
#USE OF MATRICES
print("Matrix a:\n", a)
print("First row:", a[0]) # this is just like a list of lists
print("element at (1,2) :", a[1, 2])   # arrays can be given comma separated indices
print(a[1, 1:3]) # and slices

print(a[:,1])
a[1, 2] = -3
print("a changed as\n",a)

a[:, 0] = [2, -1, 5]
print ("see how first row is changed")
print(a)

In [ ]:
#asarray
#This function is similar to numpy.
#It is useful for converting Python sequence into ndarray.
import numpy as np 
x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

In [ ]:
import numpy as np 
s = list('Hello World')
a = np.asarray(s, dtype = 'S1') 
print (a)

In [ ]:
#COMPLEX DATA TYPE
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]  # create a list 
a = np.array(l)  # convert a list to an array 
print(a) 
print (a.shape)
print(a.dtype)  # get type of an array 
M = np.array([[1+2j, 2-0.5j], [3, 4]], dtype=complex)
print (M)

In [ ]:
#Creating numpy arrays -using creation functions
x = np.arange(0, 10, 1) # arguments: start, stop, step
print (x)
y=np.linspace(0, 10, 25) #arguments: start,stop,no.of points
print (y)
y = y.astype('complex')
print (y)

In [ ]:
#more examples for "arrange"
d = np.arange(5)  # just like range() 
print(d) 
d[1] = 9.7 
print(d)  # arrays keep their type even if elements changed 
print(d*0.4)  # operations create a new array, with new type 
d = np.arange(5, dtype=numpy.float)  
print(d) 
y=np.arange(3, 7, 0.5)  # arbitrary start, stop and step 
z=np.array([ 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5]) 
print (y,z)


In [ ]:
#np.arrange different uses
x = np.arange(10)
print ("x =",x)
y = np.arange(5,10)
z = np.arange(5,10,0.5)
print (z)

#reshape to a different dimension
zz = np.arange(1,10).reshape(3,3)
print (zz)


In [ ]:
#linspace
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
N = 8
y = np.zeros(N)
x1 = np.linspace(0, 10, N, endpoint=True)
p1 = plt.plot(x1, y, 'o')
ax.set_xlim([-0.5,10.5])
plt.show()

In [ ]:
#linspace to create linearly spaced matrix-like things
#For the first column; from 1 of (1,2) to 10 of (10,20), 
#put the increasing 10 numbers.
#For the second column; from 2 of (1,2) to 20 of (10,20), 
#put the incresing 10 numbers.
matr = np.linspace((1,2),(10,20),5)
print (matr)
print (matr[1])

In [ ]:
#array creation and use
#mgrid
#random values in ndarrays
x,y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
print (x)
print (y)
# random data
z=np.random.rand(5,5)
print (z)

In [ ]:
#Creating arrays
# a diagonal matrix
a=np.diag([1,2,3])
print (a)
b = np.zeros(5) 
print(b) 
print (b.dtype)
n = 1000 
my_int_array = np.zeros(n, dtype=np.int) 
print (my_int_array.dtype) 
c = np.ones((3,3))
print (c)

In [ ]:
#useful ndarray functions : sum, max, min, mean
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ("x array is\n",x)
print ("ndim:",x.ndim)
print ("Axis-0 sum is {}".format(x.sum(axis=0)))
print ("Axis-1 sum is {}".format(x.sum(axis=1)))
print ("Axis-0 max is {}".format(x.max(axis=0)))
print ("Axis-1 min is {}".format(x.min(axis=1)))
print ("Axis-1 mean is {}".format(x.mean(axis=1)))
print ("Global sum is {}".format(x.sum()))

In [ ]:
#other functions
#note that you can specify axis value in each of the functions
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5]) 
print (arr.sum())
print (arr.mean())
print (arr.std()) 
print (arr.max())
print (arr.min())
print (div_by_3.all()) 
print (div_by_3.any()) 
print (div_by_3.sum()) 
print (div_by_3.nonzero()) 

In [ ]:
#file I/O
import os
print(os.system('head testdata.txt'))
data = np.genfromtxt('testdata.txt', delimiter=',', skip_header=1)
print (data.shape)
print (data)
np.savetxt('datasaved.txt', data)

In [ ]:
#file I/O
M = np.random.rand(3,3)
print (M)
np.save('saved-matrix.npy', M)    #binary format!
N=np.load('saved-matrix.npy')
print (N)
print (N.ndim, N.shape)

In [ ]:
#numpy arrays are mutable
#be careful when you create 
#another copy of an nd array
x = np.array([1,2,3,4])
y = x
print (x is y)
print (id(x), id(y))
x[0] = 9
print (y)
x[0] = 1
z = x[:]
print (x is z)
print (id(x), id(z))
x[0] = 8
print (z)

In [ ]:
#numpy ndarray basic operations
a = np.array([3,4,5])
b = np.ones(3)
print ("a-b:", a - b)

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print ("a:\n",a)
print ("b:\n",b)
print ("a*b:\n", a * b)
print ("dot product of a and b:\n",np.dot(a,b))

In [ ]:
#special addition and
#multiplication operators
a = np.zeros((2,2),dtype='float')
a += 5
print (a)
a *= 5
print (a)
a = a + 2*a
print (a)

In [ ]:
#Concatenation of arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
a_h = np.hstack([a,b,c]) #horizontal stack
a_v = np.vstack([a,b,c])
print (a_h)
print (a_v)

In [ ]:
#array sort
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5]) 
arr.sort()  # acts on array itself 
print(arr) 
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5]) 
print ("x is\n",x)
xx=np.sort(x) 
print (xx)
print(x) 
s = x.argsort() #sorts indice no.s wrt corresponding values
print (s) 
print (x[s]) 

In [ ]:
#array creation and use -misc uses
a = np.arange(4.0) 
print(a)
b = a * 23.4 
c = b/(a+1) 
c += 10 
print (c)
arr = np.arange(100, 200) 
select = [5, 25, 50, 75, -5] 
print(arr[select])  # can use integer lists as indices 
arr = np.arange(10, 20 )
div_by_3 = arr%3 == 0  # comparison produces boolean array 
print(div_by_3) 
print(arr[div_by_3])  # can use boolean lists as indices 
arr = np.arange(10, 20).reshape((2,5))
print (arr)

In [ ]:
#common mathematical functions
x = np.arange(1,5)
result = np.sqrt(x) * np.pi
print (result)
print (np.power(2,4)) #much faster than python equivalent
print (x.max() - x.min())

#exponential & log
arr = np.array([10,8,4])
print(np.exp(arr)) #e^x
print (np.log(arr)) #ln(x), base is e
print ("e :", np.e, "pi:", np.pi)
print (np.log10(arr)) #log(x), base is 10
print (np.log2(arr)) #log(x), base is 2

#rounding
print ("\nROUNDING")
arr = np.array([20.8999,67.89899,54.23409])  
print(np.around(arr,2)) #round off with 2 decimals
print(np.floor(arr)) #largest integer less than input number
print(np.ceil(arr))  #smallest integer greater than input number

#trigonometric
print ("\nTRIGONOMETRIC FUNCTIONS")
arr = np.array([0, 30, 60, 90, 120, 150, 180])   
print(np.sin(arr * np.pi / 180)) #sine function
print(np.cos(arr * np.pi / 180)) #cosine
print(np.tan(arr * np.pi / 180)) #tangent
arr = np.array([0.5, 0.30, 0.67])
print(np.arcsin(arr)*180/np.pi) #inverse sine function
arr = np.array([30,60,90])
print(np.sinh(arr * np.pi / 180)) #hyperbolic sine
arr = np.array([1,2,3])
print(np.arctanh(arr * np.pi / 180)) #hyperbolic inverse tangent

#complex
print ("\nCOMPLEX NUMBERS")
arr = np.array([1+2j])  
print(np.isreal(arr)) #real test funtion
print(np.conj(arr)) #conjugate funtion

In [ ]:
#statistics
a = np.array([1, 4, 3, 8, 9, 2, 3], float) 
print ("median:",np.median(a))
b = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float) 
c = np.corrcoef(b) 
print ("Correlation:", c)
d = np.corrcoef(a,a)
print ("Correlation:", d)
a = np.array([1,2,3,4,6,7,8,9])
b = np.array([2,4,6,8,10,12,13,15])
c = np.array([-1,-2,-2,-3,-4,-6,-7,-8])
print (np.corrcoef([a,b,c]))
print ("Covariance: ", np.cov(a)) #covariance
print ("Variance: ", np.var(a)) #covariance
print ("Standard deviation: ", np.std(a)) #covariance

In [ ]:
#numpy linear algebra package : linalg
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

#solving linear eqn systems
b = [1,2,3]
x = np.linalg.solve(A,b)
print ("Solution vector:", x)

#Eigenvalues and eigen vectors
#Creating an array using diag function
a = np.diag((1, 2, 3))
print("Array is :",a)
 
# calculating an eigen value using eigvals() function
c = np.linalg.eigvals(a)
print("Eigen value is :",c)
    
# calculating an eigen value using eig() function
c, d = np.linalg.eig(a)
print("Eigen value is :",c)
print("Eigen vector is :",d)


In [ ]:
# ARRAY INDEXING
# Create the following  2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print ("a is :\n", a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print ("b is now:\n",b)

In [ ]:
#misc ndarray operations
print(a[0])  # this is just like a list of lists 
print(a[1][2])  #print a single value ==> 7 will be written
print(a[1, 2])  # arrays can be given comma separated indices 
print(a[1, 1:3])  # and slices 
print(a[:,1]) 
a[1, 2] = 7 
print(a) 
a[:, 0] = [0, 9, 8] 
print(a) 

In [ ]:
#BOOLEAN ARRAY INDEXING
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)  # Find the elements which are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print (bool_idx)
print (a[a > 2])

In [ ]:
#USE OF MATRICES
print(a) 
print(a[0])  # this is just like a list of lists 
print(a[1, 2])  # arrays can be given comma separated indices 
print(a[1, 1:3])  # and slices 
print(a[:,1]) 
a[1, 2] = 7 
print(a) 
a[:, 0] = [0, 9, 8] 
print(a) 

In [ ]:
#matrices -different definitions
m = np.mat([[1,2],[3,4]]) 
print (m)
a = np.array([[1,2],[3,4]]) 
print (a)
m = np.mat(a) 
print (m)
#or 
a = np.array([[1,2],[3,4]]) 
print (a)
m = np.asmatrix(a)
print (m)

In [ ]:
#MATRICES
#array vs matrix
a = np.array([[1,2],[3,4]]) 
m = np.mat(a) # convert 2-d array to matrix 
m = np.matrix([[1, 2], [3, 4]]) 
print ("ndarray:\n",a)
print ("matrix:\n",m)
print (a[0]) # result is 1-dimensional
print (m[0])    # result is 2-dimensional 
print ("a*a :\n", a*a) # element-by-element multiplication  
print ("m*m :\n", m*m)    # algebraic) matrix multiplication 
print (a**3)    # element-wise power 
print (m**3)    # matrix multiplication m*m*m 
print (m.T) # transpose of the matrix 
print (m.H)  # conjugate transpose (differs from .T for complex matrices) 
print (m.I) # inverse matrix 

In [ ]:
#array math
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
v1 = np.arange(0, 5)
print (A)
print (v1)
print (np.dot(A,A))
print (np.dot(A,v1))
print (np.dot(v1,v1))

In [ ]:
#Alternatively, we can cast the array objects to the type matrix. 
#This changes the behavior of the standard arithmetic 
#operators +, -, * to use matrix algebra.
M = np.matrix(A)
v = np.matrix(v1).T
print (v)
print (M*v)
print (v.T * v)   # inner product
# standard matrix algebra applies
print (v + M*v)

In [ ]:
#numpy FFT :-)
#optional topic
from numpy import fft
import numpy as np
import matplotlib.pyplot as plt
n = 1000    # Number of data points
dx= 5.0    # Sampling period (in meters)
x = dx*np.arange(0,n)   # x coordinates
w1 = 100.0  # wavelength (meters)
w2 = 20.0   # wavelength (meters)
fx= np.sin(2*np.pi*x/w1) + 2*np.cos(2*np.pi*x/w2) # signal
Fk= fft.fft(fx)/n    # Fourier coefficients (divided by n)
nu= fft.fftfreq(n,dx)  # Natural frequencies
Fk= fft.fftshift(Fk)   # Shift zero freq to center
nu= fft.fftshift(nu)   # Shift zero freq to center
f, ax = plt.subplots(3,1,sharex=True)
ax[0].plot(nu, np.real(Fk))   # Plot Cosine terms
ax[0].set_ylabel(r'$Re[F_k]$', size = 'x-large')
ax[1].plot(nu, np.imag(Fk))         # Plot Sine terms
ax[1].set_ylabel(r'$Im[F_k]$', size = 'x-large')
ax[2].plot(nu, np.absolute(Fk)**2)  # Plot spectral power
ax[2].set_ylabel(r'$\vert F_k\vert ^2$', size = 'x-large')
ax[2].set_xlabel(r'$\widetilde{\nu}$', size = 'x-large')
plt.show()